Matrix task
dkaznacheev/SpbAU-Java pull request #2
Opened 2017-09-26 19:06 UTC by dkaznacheev

2017-10-16 18:10 UTC, yurii-litvinov requested changes
Папку .gradle надо добавить в .gitignore, её не надо выкладывать. .workspace.xml тоже в гите не нужен, тоже добавляйте его в .gitignore

2017-10-16 18:10 UTC, yurii-litvinov commented on SpiralMatrix/src/main/java/MatrixTask.java
> +public class MatrixTask {
Классы вне пакетов стайлгайдом не рекомендуются. Классы без комментариев к самому классу не рекомендуются условием домашки :)

2017-10-16 18:10 UTC, yurii-litvinov commented on SpiralMatrix/src/main/java/MatrixTask.java
> +
Перед "}" пустая строка обычно не ставится

2017-10-16 18:10 UTC, yurii-litvinov commented on SpiralMatrix/src/main/java/MatrixTask.java
> +    public static void sortColumns (int[][] matrix) {
Опять-таки, пробел перед "(" не ставится

2017-10-16 18:10 UTC, yurii-litvinov commented on SpiralMatrix/src/main/java/MatrixTask.java
> +            return;
Лучше заключать в фигурные скобки

2017-10-16 18:10 UTC, yurii-litvinov commented on SpiralMatrix/src/main/java/MatrixTask.java
> +        copyTransposed(matrix, transposed);
Оно не упадёт только если все массивы в матрице имеют одинаковую длину, что для public static-метода слишком смелое допущение. Надо бы ввести какую-то проверку

2017-10-16 18:10 UTC, yurii-litvinov commented on SpiralMatrix/src/test/java/MatrixTaskTest.java
> +        assert(result.charAt(0) == '1');
assertEquals

2017-10-16 18:10 UTC, yurii-litvinov commented on SpiralMatrix/src/test/java/MatrixTaskTest.java
> +            assert(result.charAt(i) - result.charAt(i - 1) == 1);
Тут тоже. assert --- это не для тестов, а для рантайм-проверок в "настоящем" коде.

2017-10-16 18:10 UTC, yurii-litvinov commented on src/ru/spbau/dkaznacheev/HashTable.java
> +package ru.spbau.dkaznacheev;
Хеш-таблица тут не совсем в тему, и чтобы так не было, для каждой задачи надо новую ветку от мастера отводить. В этот раз, впрочем, можно не править, а то вообще всё сломается, скорее всего :)

2017-10-16 18:10 UTC, yurii-litvinov commented on SpiralMatrix/src/test/java/MatrixTaskTest.java
> +    public void sortColumns() throws Exception {
Нужны более говорящие имена тестов

2017-10-16 18:10 UTC, yurii-litvinov commented on SpiralMatrix/src/test/java/MatrixTaskTest.java
> +}
Нужны ещё тесты на всякие "плохие" ситуации типа "рваных массивов" (двумерных массивов с разной длиной) или null-ов в качестве параметров. public-методы не должны доверять своему вводу, а программа должна адекватно реагировать на такую фигню

2017-10-31 13:54 UTC, yurii-litvinov requested changes
Всё равно что-то пошло не так и куча бинарников закоммитилась. И workspace.xml. В этот раз снимать баллы за это не буду, но дальше это сразу -2 балла без права исправления :) Надо .gitignore

2017-10-31 13:54 UTC, yurii-litvinov commented on SpiralMatrix/src/main/java/NullRowException.java
> +public class NullRowException extends Throwable {
Ему тоже нужны комментарии

2017-10-31 13:54 UTC, yurii-litvinov commented on SpiralMatrix/src/main/java/UnevenRowsException.java
> +public class UnevenRowsException extends Exception {
И тут

2017-10-31 13:54 UTC, yurii-litvinov commented on SpiralMatrix/src/test/java/MatrixTaskTest.java
> +        } catch (NullRowException e) {
Ловить исключения в тесте, как правило, ошибка, используйте expected или assertThrows

2017-10-31 13:54 UTC, yurii-litvinov commented on SpiralMatrix/src/test/java/MatrixTaskTest.java
> +            assertTrue(true);
Оно вообще ничего не делает :)

2017-10-31 13:54 UTC, yurii-litvinov commented on SpiralMatrix/src/test/java/MatrixTaskTest.java
> +            assert(result.charAt(i) - result.charAt(i - 1) == 1);
Напоминаю

2017-12-07 16:57 UTC, yurii-litvinov requested changes
Ещё чуть-чуть

2017-12-07 16:57 UTC, yurii-litvinov commented on HW2/SpiralMatrix/src/test/java/MatrixTaskTest.java
> +            assertTrue(false);
Не-а, нельзя ловить исключения в тестах. Особенно так ужасно, fail() же есть :)

2017-12-07 17:38 UTC, dkaznacheev commented on HW2/SpiralMatrix/src/test/java/MatrixTaskTest.java
> +            assertTrue(false);
Ой-ой-ой, я просто это не заметил. Я думал, я убрал все штуки такого рода

2017-12-07 18:28 UTC, yurii-litvinov approved these changes
Есть ещё недобитые assert-ы, но ладно, зачтена

2017-12-07 18:28 UTC, yurii-litvinov commented on HW2/SpiralMatrix/src/test/java/MatrixTaskTest.java
> +        assert(result.charAt(0) == '1');
assertEquals :)

2017-12-07 18:28 UTC, yurii-litvinov commented on HW2/SpiralMatrix/src/test/java/MatrixTaskTest.java
> +    @Test (expected = NullRowException.class)
ПРобел тут обычно перед "(" не ставится

2017-12-07 18:28 UTC, yurii-litvinov commented on HW2/SpiralMatrix/src/test/java/MatrixTaskTest.java
> +
Лишняя пустая строчка :) Перед "}" пустые строки ставить не принято

2018-03-04 13:38 UTC, merged